name: Deploy Astro Website to Hosting

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ storyblok_publish ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie kodu bez sprawdzania historii Gita (zapobiega exit code 128)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Konfiguracja Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalacja zależności i budowanie pliku dist
      - name: Install dependencies & Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      # 4. Wgrywanie plików przez FTP
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./dist/