name: Deploy Astro Website to Hosting

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ storyblok_publish ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie kodu
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Konfiguracja Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalacja zależności i budowanie projektu
      - name: Install dependencies & Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      # 4. Bezpośrednie przesyłanie wygenerowanych plików z ./dist/ na serwer FTP
      - name: Sync files via FTP
        uses: wlixcc/SFTP-Deploy-Action@v1.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: ${{ secrets.FTP_SERVER_DIR }}
          sftp: false