name: Deploy Astro Website to Hosting

on:
  push:
    branches: [ main ] # Uruchamia się po każdym pushu do gałęzi main
  repository_dispatch:
    types: [ storyblok_publish ] # Uruchamia się po kliknięciu Publish w Storybloku
  workflow_dispatch: # Pozwala ręcznie kliknąć "Deploy" na GitHubie

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie kodu z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Konfiguracja Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalacja zależności i budowanie pliku dist
      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build

      # 4. Wszycie automatycznego transferu plików FTP
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./dist/
          dangerous-clean-slate: false # Zabezpieczenie przed usuwaniem innych plików na serwerze